apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: submission-listener
  namespace: ab-eval-flow
spec:
  serviceAccountName: pipeline
  triggers:
    - name: submission-pr-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: >-
                header.match('X-GitHub-Event', 'pull_request') &&
                body.action in ['opened', 'synchronize', 'reopened'] &&
                body.pull_request.base.ref == 'main' &&
                body.pull_request.head.ref.startsWith('eval/')
            - name: "overlays"
              value:
                - key: submission_directory
                  expression: >-
                    body.pull_request.head.ref.split('/')[1]
      bindings:
        - ref: submission-binding
      template:
        ref: submission-template
